[versions]
androidGradlePlugin = "8.3.2"
kotlin = "1.9.23"
navigationComponent = "2.6.0"

kotlinCoroutine = "1.7.2"

androidxCoreKtx = "1.3.2"
androidxAppcompat = "1.6.0"
androidxFragment = "1.3.0"
androidxConstraintlayout = "2.0.4"
googleMaterial = "1.4.0-alpha01"
androidxPreferences = "1.1.1"
androidxRoom = "2.6.1"

composeBom = "2023.01.00"
composeRuntime = "1.0.0"
composeActivity = "1.6.1"
composeViewmodel = "2.5.1"

googleAccompanistPermissions = "0.34.0"

squareRetrofit = "2.9.0"
squareOkhttp = "4.9.0"
jakewhartonTimber = "4.7.1"
bumptechGlide = "4.11.0"
koinBoom = "3.5.6"
hbisoftPickit = "0.1.14"
karumiDexter = "6.2.2"
hdodenhofCircleimageview = "3.1.0"
facebookShimmer = "0.5.0"
coil = "2.6.0"

androidxTestJunit = "1.1.3"
androidxTestCore = "1.4.0"
robolectric = "4.6"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCoreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "googleMaterial" }

koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koinBoom" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-android-compose = { module = "io.insert-koin:koin-androidx-compose" }
koin-core = { module = "io.insert-koin:koin-core" }

bumptech-glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "bumptechGlide" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinCoroutine" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinCoroutine" }
androidx-fragment = { group = "androidx.fragment", name = "fragment", version.ref = "androidxFragment" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidxFragment" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidxConstraintlayout" }
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationComponent" }
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationComponent" }
jakewharton-timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "jakewhartonTimber" }
bumptech-glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "bumptechGlide" }
hbisoft-pickit = { group = "com.github.HBiSoft", name = "PickiT", version.ref = "hbisoftPickit" }
karumi-dexter = { group = "com.karumi", name = "dexter", version.ref = "karumiDexter" }
hdodenhof-circleimageview = { group = "de.hdodenhof", name = "circleimageview", version.ref = "hdodenhofCircleimageview" }
facebook-shimmer = { group = "com.facebook.shimmer", name = "shimmer", version.ref = "facebookShimmer" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "composeRuntime" }
androidx-compose-activity = { group = "androidx.activity", name = "activity", version.ref = "composeActivity" }
androidx-compose-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "composeViewmodel" }
androidx-compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-material = { module = "androidx.compose.material:material" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
google-accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "googleAccompanistPermissions" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidxRoom" }
square-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "squareRetrofit" }
square-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "squareRetrofit" }
square-okhttp-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "squareOkhttp" }
androidx-preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "androidxPreferences" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidxRoom" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidxRoom" }

androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestJunit" }
androidx-test-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestJunit" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidxTestCore" }
androidx-test-core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "androidxTestCore" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

